name: mkvtoolnix-jz
version: '25.0.0'
summary: MKVToolNix is a set of tools to create, alter and inspect Matroska files
description: |
 Matroska is an extensible, open source, open standard Multimedia container.
 Matroska is usually found as .MKV files (matroska video), .MKA files (matroska 
 audio) and .MKS files (subtitles) and .MK3D files (stereoscopic/3D video).
 It is also the basis for .webm (WebM) files.
grade: stable
confinement: strict
base: core18

apps:
  gui:
    command: desktop-launch mkvtoolnix-gui
    plugs: [process-control, network-bind, home, desktop, desktop-legacy, x11, wayland]
  extract:
    command: desktop-launch mkvextract
    plugs: [process-control, home]
  info:
    command: desktop-launch mkvinfo
    plugs: [process-control, home, desktop, desktop-legacy, x11, wayland]
  merge:
    command: desktop-launch mkvmerge
    plugs: [process-control, home]
  propedit:
    command: desktop-launch mkvpropedit
    plugs: [process-control, home]

parts:
  mkvtoolnix:
    plugin: autorake
    source: https://mkvtoolnix.download/sources/mkvtoolnix-25.0.0.tar.xz
    after: [libmatroska, desktop-qt5, libcmark]
    build-packages:
      - libboost-math-dev
      - libboost-regex-dev
      - libbz2-dev
      - libflac-dev
      - libmagic-dev
      - libogg-dev
      - libpcre3-dev
      - libvorbis-dev
      - libgtest-dev
      - pandoc
      - docbook-xsl
      - xsltproc
      - ruby
      - liblzo2-dev
      - zlib1g-dev
      - libcurl4-gnutls-dev
      - pkg-config
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libpugixml-dev
      - qt5-default
      - qtmultimedia5-dev
    stage-packages:
      - libmagic1
    prime:
      - -share/applications
      - -share/man
    override-build: |
      snapcraftctl build
      echo Stripping
      strip $SNAPCRAFT_PART_INSTALL/bin/* 2>/dev/null || /bin/true

  libebml:
    plugin: cmake
    source: https://dl.matroska.org/downloads/libebml/libebml-1.3.6.tar.xz
    build-packages:
      - pkg-config
      - g++
    prime:
      - -include
      - -lib/*.a
      - -lib/pkgconfig

  libcmark:
    plugin: cmake
    source: https://github.com/commonmark/cmark.git
    source-type: git
    source-tag: 0.28.3
    prime:
      - -include
      - -lib/cmake
      - -lib/*.a
      - -lib/pkgconfig

  libmatroska:
    plugin: cmake
    source: https://dl.matroska.org/downloads/libmatroska/libmatroska-1.4.9.tar.xz
    after: [libebml]
    build-packages:
      - pkg-config
      - g++
    prime:
      - -include
      - -lib/*.a
      - -lib/pkgconfig

  desktop-qt5:
    prime:
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var
