name: matroska-tools
version: '14.0.0-4'
summary: MKVToolNix is a set of tools to create, alter and inspect Matroska files
description: |
 Matroska is an extensible, open source, open standard Multimedia container.
 Matroska is usually found as .MKV files (matroska video), .MKA files (matroska 
 audio) and .MKS files (subtitles) and .MK3D files (stereoscopic/3D video).
 It is also the basis for .webm (WebM) files.
grade: stable
confinement: strict

apps:
  gui:
    command: desktop-launch mkvtoolnix-gui
    plugs: [process-control, network-bind, home, unity7]
  extract:
    command: desktop-launch mkvextract
    plugs: [process-control, home]
  info:
    command: desktop-launch mkvinfo
    plugs: [process-control, home, unity7]
  merge:
    command: desktop-launch mkvmerge
    plugs: [process-control, home]
  propedit:
    command: desktop-launch mkvpropedit
    plugs: [process-control, home]

parts:
  mkvtoolnix:
    plugin: autorake
    source: https://mkvtoolnix.download/sources/mkvtoolnix-14.0.0.tar.xz
    after: [libmatroska, desktop-qt5]
    build-packages:
      - libboost-math-dev
      - libboost-regex-dev
      - libbz2-dev
      - libflac-dev
      - libmagic-dev
      - libogg-dev
      - libpcre3-dev
      - libvorbis-dev
      - libgtest-dev
      - pandoc
      - docbook-xsl
      - xsltproc
      - ruby
      - liblzo2-dev
      - zlib1g-dev
      - libcurl4-gnutls-dev
      - pkg-config
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libpugixml-dev
      - qt5-default
      - qtmultimedia5-dev
    stage-packages:
      - gnome-themes-standard
      - libqt5libqgtk2
      - gtk2-engines-pixbuf
      - libpng12-0
    prime:
      - -share/applications
      - -share/man
    install: |
      echo Stripping
      strip $SNAPCRAFT_PART_INSTALL/bin/* 2>/dev/null || /bin/true

  libebml:
    plugin: autotools
    source: https://dl.matroska.org/downloads/libebml/libebml-1.3.4.tar.bz2
    build-packages:
      - pkg-config
      - g++
    prime:
      - -include
      - -lib/*.a
      - -lib/pkgconfig

  libmatroska:
    plugin: autotools
    source: https://dl.matroska.org/downloads/libmatroska/libmatroska-1.4.7.tar.bz2
    after: [libebml]
    build-packages:
      - pkg-config
      - g++
    prime:
      - -include
      - -lib/*.a
      - -lib/pkgconfig

  desktop-qt5:
    prime:
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var
